/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab2;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Locale;
import java.util.Map;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.event.ListDataListener;
import org.math.plot.Plot2DPanel;

/**
 *
 * @author Vova
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        buttonGroup2.add(jRadioButton1);
        buttonGroup2.add(jRadioButton2);
        buttonGroup2.add(jRadioButton3);
        buttonGroup2.add(jRadioButton4);
        buttonGroup1.add(jRadioButton5);
        buttonGroup1.add(jRadioButton6);
        buttonGroup3.add(jRadioButton7);
        buttonGroup3.add(jRadioButton8);
        buttonGroup3.add(jRadioButton9);
        jRadioButton9.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel6 = new javax.swing.JPanel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lab_2");
        setPreferredSize(new java.awt.Dimension(880, 600));
        setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Размерности"));

        jLabel4.setText("X1");

        jLabel5.setText("X2");

        jLabel6.setText("X3");

        jLabel7.setText("Y");

        jTextField4.setText("2");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.setText("2");

        jTextField6.setText("3");

        jTextField7.setText("4");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel4, jLabel5, jLabel6, jLabel7});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("График"));

        jButton3.setText("Построить график");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Y1", "Y2", "Y3", "Y4" }));

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Нормировать");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1)))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Данные"));
        jPanel1.setName(""); // NOI18N

        jLabel3.setText("Входные данные");

        jLabel2.setText("Размер выборки");

        jTextField1.setText("45");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("input.txt");

        jLabel1.setText("Исходные данные");

        jButton1.setText("Открыть");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField3.setText("output.txt");

        jButton2.setText("Выбрать");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField2, jTextField3});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Подсчёт лямбда"));

        jRadioButton5.setSelected(true);
        jRadioButton5.setText("В одной системе");

        jRadioButton6.setText("В трёх системах");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton6)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Тип полинома"));

        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Чебышев");

        jRadioButton2.setText("Лаггер");

        jRadioButton3.setText("Эрмит");

        jRadioButton4.setText("Лежандр");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton4)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jRadioButton1, jRadioButton2, jRadioButton3, jRadioButton4});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jRadioButton1, jRadioButton2, jRadioButton3, jRadioButton4});

        jButton4.setText("Запустить");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Степени полиномов"));

        jLabel8.setText("при X1");

        jTextField8.setText("7");

        jLabel9.setText("при X2");

        jLabel10.setText("при X3");

        jTextField9.setText("7");

        jTextField10.setText("7");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField10))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jTextPane1);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Подсчёт b0"));

        jRadioButton7.setText("Нормированные Y");

        jRadioButton8.setSelected(true);
        jRadioButton8.setText("через минимум и максимум");

        jRadioButton9.setText("Среднее значение Y");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton9))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jRadioButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton9)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(3, 3, 3)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser fileopen = new JFileChooser();
        int ret = fileopen.showDialog(null, "Выбрать файл");
        if (ret == JFileChooser.APPROVE_OPTION) {
            resultFile = fileopen.getSelectedFile();
            jTextField3.setText(openFile.getAbsolutePath());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fileopen = new JFileChooser();
        int ret = fileopen.showDialog(null, "Открыть файл");
        if (ret == JFileChooser.APPROVE_OPTION) {
            openFile = fileopen.getSelectedFile();
            jTextField2.setText(openFile.getAbsolutePath());
        }
//new OpenFile().setVisible(true);
        //jFileChooser1.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTextPane1.setText("");
        try {
            //Launch program
            openFile.createNewFile();
            resultFile.createNewFile();
            //System.out.println(openFile.getAbsolutePath());
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        int length = Integer.parseInt(jTextField1.getText());
        n1 = Integer.parseInt(jTextField4.getText());
        n2 = Integer.parseInt(jTextField5.getText());
        n3 = Integer.parseInt(jTextField6.getText());
        p1 = Integer.parseInt(jTextField8.getText());

        p2 = Integer.parseInt(jTextField9.getText());

        p3 = Integer.parseInt(jTextField10.getText());
        m = Integer.parseInt(jTextField7.getText());
        x1 = new double[n1][length];
        x2 = new double[n2][length];
        x3 = new double[n3][length];
        y = new double[m][length];
        xG = new double[length];

        for (int i = 0; i < length; i++) {
            xG[i] = i;
        }
        String[] list = new String[m];
        for (int i = 1; i <= m; i++) {
            list[i - 1] = "Y" + i;
        }
        jComboBox1.setModel(new DefaultComboBoxModel(list));
        Scanner sc = null;
        PrintWriter pw = null;
        try {

            sc = new Scanner(openFile);
            sc.useLocale(Locale.US);
            for (int i = 0; i < length; i++) {
                for (int j = 0; j < x1.length; j++) {
                    x1[j][i] = sc.nextDouble();
                }
                for (int j = 0; j < x2.length; j++) {
                    x2[j][i] = sc.nextDouble();
                }
                for (int j = 0; j < x3.length; j++) {
                    x3[j][i] = sc.nextDouble();
                }
                for (int j = 0; j < y.length; j++) {
                    y[j][i] = sc.nextDouble();
                }
            }


        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            sc.close();
        }
//        try {
//            PrintWriter pw1 = new PrintWriter("input1.txt");
//            for (int i = 0; i < length; i++) {
//                for (int j = 0; j < x1.length; j++) {
//                    pw1.printf(Locale.US,x1[j][i] + "\t\t");
//                }
//                for (int j = 0; j < x2.length; j++) {
//                    pw1.print(x2[j][i] + "\t\t");
//                }
//                for (int j = 0; j < x3.length; j++) {
//                    pw1.print(x3[j][i] + "\t\t");
//                }
//                for (int j = 0; j < y.length; j++) {
//                    pw1.print(y[j][i] + "\t\t");
//                }
//                pw1.println();
//            }
//            pw1.close();
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
        x1N = Work.norm(x1);
        x2N = Work.norm(x2);
        x3N = Work.norm(x3);
        yN = Work.norm(y);

        if (jRadioButton7.isSelected()) {
            //
            bq0 = yN;
        }
        if (jRadioButton8.isSelected()) {
            bq0 = Work.bq0(0, yN);

        }
        if (jRadioButton9.isSelected()) {
            bq0 = Work.bq01(0, yN);

        }
        
        Polinom pol = null;
        if (jRadioButton1.isSelected()) {
            pol = new Chebyshev();
        }
        if (jRadioButton2.isSelected()) {
            pol = new Lagger();
        }
        if (jRadioButton3.isSelected()) {
            pol = new Ermit();
        }
        if (jRadioButton4.isSelected()) {
            pol = new Lejandra();
        }
        Psi[] psi = new Psi[m];
        double[][] maxx = Work.max(x1, x2, x3);
        double[][] minx = Work.min(x1, x2, x3);
        Matr lambda = null;
        try {
            pw = new PrintWriter(resultFile);

            for (int i = 0; i < m; i++) {
                if (jRadioButton5.isSelected()) {
//            F_1 f_1 = new F_1(n1, n2, n3, p1, p2, p3, pol, x1, x2, x3, bq0);
//            lambda = Work.minimization(f_1, new Matr(n1, p1, n2, p2, n3, p3));
                    double[][] f_1 = Work.f_1(pol, new int[]{n1, n2, n3}, new int[]{p1, p2, p3}, x1N, x2N, x3N);
                    double[] lambda_i = Work.conjGradMethod(f_1, bq0[i]);
                    lambda = new Matr(n1, p1 + 1, n2, p2 + 1, n3, p3 + 1, lambda_i);
                    psi[i] = new Psi(n1, n2, n3, p1, p2, p3, pol, lambda, maxx, minx);
//                    Work.nevyazka(psi[i], bq0[i], x1N, x2N, x3N);
                    write(lambda.toString("lambda " + i + "\r\n"));
                    pw.println(lambda.toString("lambda " + i + "\r\n"));
//                    System.out.println("f_1");
//                    for (int k = 0; k < f_1.length; k++) {
//                        for (int h = 0; h < f_1[0].length; h++) {
//                            System.out.printf("%.4f \t",f_1[k][h]-A[k][h]);
//                        }
//                        System.out.println("");
//                    }
                    // System.out.println("psi");
                } else if (jRadioButton6.isSelected()) {
//            F_1 f_11 = new F_1(n1, 0, 0, p1, 0, 0, pol, x1, x2, x3, bq0);
//            Matr lambda1 = Work.minimization(f_11, new Matr(n1, p1, 0, 0, 0, 0));
//            F_1 f_12 = new F_1(0, n2, 0, 0, p2, 0, pol, x1, x2, x3, bq0);
//            Matr lambda2 = Work.minimization(f_12, new Matr(0, 0, n2, p2, 0, 0));
//            F_1 f_13 = new F_1(0, 0, n3, 0, 0, p3, pol, x1, x2, x3, bq0);
//            Matr lambda3 = Work.minimization(f_13, new Matr(0, 0, 0, 0, n3, p3));
//            lambda = new Matr(lambda1.getX1(), lambda2.getX2(), lambda3.getX3());
                    double[] lambda_i_1 = Work.conjGradMethod(Work.f_1(pol, new int[]{n1, 0, 0}, new int[]{p1, 0, 0}, x1N, x2N, x3N), bq0[i]);
                    double[] lambda_i_2 = Work.conjGradMethod(Work.f_1(pol, new int[]{0, n2, 0}, new int[]{0, p2, 0}, x1N, x2N, x3N), bq0[i]);
                    double[] lambda_i_3 = Work.conjGradMethod(Work.f_1(pol, new int[]{0, 0, n3}, new int[]{0, 0, p3}, x1N, x2N, x3N), bq0[i]);
                    double[] lambda_i = new double[lambda_i_1.length + lambda_i_2.length + lambda_i_3.length];
                    System.arraycopy(lambda_i_1, 0, lambda_i, 0, lambda_i_1.length);
                    System.arraycopy(lambda_i_2, 0, lambda_i, lambda_i_1.length, lambda_i_2.length);
                    System.arraycopy(lambda_i_3, 0, lambda_i, lambda_i_1.length + lambda_i_2.length, lambda_i_3.length);
                    lambda = new Matr(n1, p1 + 1, n2, p2 + 1, n3, p3 + 1, lambda_i);
                    psi[i] = new Psi(n1, n2, n3, p1, p2, p3, pol, lambda, maxx, minx);
                    write(lambda.toString("lambda " + i + "\r\n"));
                    pw.println(lambda.toString("lambda " + i + "\r\n"));
                }
            }
            //      psi = new Psi(n1, n2, n3, p1, p2, p3, pol, lambda);
            double[][] a1 = new double[m][];
            double[][] a2 = new double[m][];
            double[][] a3 = new double[m][];
            for (int i = 0; i < m; i++) {
//            Matr a;
//            F_2 fi21 = new F_2(psi, x1, y[i], 1);
//            a = Work.minimization(fi21, new Matr(1, n1, 0, 0, 0, 0));
//            for (int j = 0; j < n1; j++) {
//                a1[i][j] = a.getX1()[0][j];
//            }
//            F_2 fi22 = new F_2(psi, x2, y[i], 2);
//            a = Work.minimization(fi22, new Matr(1, n2, 0, 0, 0, 0));
//            for (int j = 0; j < n2; j++) {
//                a2[i][j] = a.getX1()[0][j];
//            }
//            F_2 fi23 = new F_2(psi, x3, y[i], 3);
//            a = Work.minimization(fi23, new Matr(1, n3, 0, 0, 0, 0));
//            for (int j = 0; j < n3; j++) {
//                a3[i][j] = a.getX1()[0][j];
//            }
////                double[][] f_2 = new double[x1N.length+x2N.length+x3N.length][];
////                double[][] f = Work.F_2(psi, x1N, 1, i);
////                for (int k = 0; k <x1.length; k++) {
////                    f_2[k] = f[k];
////                }
////                f = Work.F_2(psi, x2N, 2, i);
////                for (int k = 0; k <x2N.length; k++) {
////                    f_2[k + x1N.length] = f[k];
////                }
////                f = Work.F_2(psi, x3N, 3, i);
////                for (int k = 0; k <x3N.length; k++) {
////                    f_2[k + x1N.length + x2N.length] = f[k];
////                }
////                double[] a = Work.Conjugate_gradient_method(f_2, yN[i]);
////                
////                    a1[i] = new double[x1N.length];
////                    System.arraycopy(a, 0, a1[i], 0, x1N.length);
////                    a2[i] = new double[x2N.length];
////                    System.arraycopy(a, x1N.length, a2[i], 0, x2N.length);
////                    a3[i] = new double[x3N.length];
////                    System.arraycopy(a, x1N.length+x2N.length, a3[i], 0, x3N.length);

                a1[i] = Work.conjGradMethod(Work.f_2(psi, x1N, 1, i), yN[i]);
                a2[i] = Work.conjGradMethod(Work.f_2(psi, x2N, 2, i), yN[i]);
                a3[i] = Work.conjGradMethod(Work.f_2(psi, x3N, 3, i), yN[i]);

            }

            Matr a = new Matr(a1, a2, a3);
            write(a.toString("a\r\n"));
            pw.println(a.toString("a\r\n"));
            Fi fi = new Fi(n1, n2, n3, psi, a);
            //System.out.println("phi");
            double[][] c1 = new double[1][m];
            double[][] c2 = new double[1][m];
            double[][] c3 = new double[1][m];
            for (int i = 0; i < m; i++) {
//            F_3 f3i = new F_3(fi, x1, x2, x3, y[i], i);
//            Matr c = Work.minimization(f3i, new Matr(1, 1, 1, 1, 1, 1));
                double[] c = Work.conjGradMethod(Work.F_3(fi, x1N, x2N, x3N, i), yN[i]);
                c1[0][i] = c[0];
                c2[0][i] = c[1];
                c3[0][i] = c[2];
                //System.out.println("c1");
            }
            //System.out.println("ph");
            Matr c = new Matr(c1, c2, c3);
            write(c.toString("c\r\n"));
            pw.println(c.toString("c\r\n"));
            Fi_i finalFunction = new Fi_i(fi, c);
            double[] maxj = new double[m];
            double[] minj = new double[m];
            for (int i = 0; i < y.length; i++) {
                maxj[i] = y[i][0];
                minj[i] = y[i][0];
                for (int j = 1; j < y[i].length; j++) {
                    if (maxj[i] < y[i][j]) {
                        maxj[i] = y[i][j];
                    } else if (minj[i] > y[i][j]) {
                        minj[i] = y[i][j];
                    }
                }

            }
            int[] n = {n1, n2, n3};
            for (int i = 0; i < m; i++) {
                for (int s = 1; s < 4; s++) {
                    for (int js = 0; js < n[s - 1]; js++) {
                        write("psi" + i + s + js + "=" + psi[i].toString(1, s, js) + "\n");
                        pw.println("psi" + i + s + js + "=" + psi[i].toString(1, s, js));
                    }
                }
            }
            for (int i = 0; i < m; i++) {
                for (int s = 1; s < 4; s++) {
                    write("Ф" + i + s + "=" + fi.toString(1, i, s) + "\n");
                    pw.println("Ф" + i + s + "=" + fi.toString(1, i, s));
                }
            }
            for (int i = 0; i < m; i++) {
                write("Ф" + i + "=" + finalFunction.toString(i) + "\n");
                pw.println("Ф" + i + "=" + finalFunction.toString(i));

            }
            pw.println("В нормированном виде");
            for (int i = 0; i < m; i++) {
                pw.println("Ф" + i + "=" + finalFunction.toStringNorm(i));

            }
            pw.println("В ненормированном виде");
            for (int i = 0; i < m; i++) {
                pw.println("Ф" + i + "=" + finalFunction.toStringNenorm(i, maxj[i] - minj[i]) + "+" + minj);

            }

            double[] x11 = new double[n1];
            double[] x12 = new double[n2];
            double[] x13 = new double[n3];
            yG = new double[m][length];
            yNG = new double[m][length];
            nevyazka = new double[m];
            pw.println("нормированные");
            for (int j = 0; j < m; j++) {
                pw.print("Y" + j + "\t\t");
            }
            pw.println();

            for (int i = 0; i < length; i++) {
                for (int j = 0; j < n1; j++) {
                    x11[j] = x1N[j][i];
                }
                for (int j = 0; j < n2; j++) {
                    x12[j] = x2N[j][i];
                }
                for (int j = 0; j < n3; j++) {
                    x13[j] = x3N[j][i];
                }

                for (int j = 0; j < m; j++) {

                    yNG[j][i] = finalFunction.func(j, x11, x12, x13);

                    if (nevyazka[j] < Math.abs(yNG[j][i] - yN[j][i])) {
                        nevyazka[j] = Math.abs(yNG[j][i] - yN[j][i]);
                    };
                    pw.print(yNG[j][i] + "\t\t");

                }
                pw.println();
            }

            pw.println("без нормировки");
            for (int j = 0; j < m; j++) {
                pw.print("Y" + j + "\t\t");
            }
            pw.println();

            for (int j = 0; j < y[0].length; j++) {
                for (int i = 0; i < y.length; i++) {
                    yG[i][j] = yNG[i][j] * (maxj[i] - minj[i]) + minj[i];
                    pw.print(yG[i][j] + "\t\t");
                }
                pw.println();
            }
            pw.println();
            pw.println("Невязка");

            for (int j = 0; j < y[0].length; j++) {
                for (int i = 0; i < y.length; i++) {

                    pw.print(Math.abs(yNG[i][j] - yN[i][j]) + "\t\t");
                }
                pw.println();
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            pw.close();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void write(String text) {

        jTextPane1.setText(jTextPane1.getText() + text);
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFrame frame = new JFrame();
        Plot2DPanel plot = new Plot2DPanel("South");
        double[][] z, b;
        if (!jCheckBox1.isSelected()) {
            z = yG;
            b = y;
        } else {
            z = yNG;
            b = yN;
        }
        plot.addLinePlot("Fi" + (jComboBox1.getSelectedIndex() + 1), xG, z[jComboBox1.getSelectedIndex()]);
        plot.addLinePlot("Y" + (jComboBox1.getSelectedIndex() + 1), xG, b[jComboBox1.getSelectedIndex()]);

        double[] a = {0, 0};
        plot.addLinePlot("Невязка = " + Double.toString(nevyazka[jComboBox1.getSelectedIndex()]), a, a);
        frame.add(plot);
        frame.setVisible(true);
        frame.pack();
        frame.setBounds(0, 0, 800, 600);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    File openFile = new File("input.txt");
    File resultFile = new File("output.txt");
    double[][] x1, x1N;
    double[][] x2, x2N;
    double[][] x3, x3N;
    double[][] y, yN;
    double[][] bq0;
    int p1, p2, p3, n1, n2, n3, m;
    double[] xG;
    double[][] yG, yNG;
    double[] nevyazka;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
